export const ActionTypes = {

    GET_DATA_REQUEST: 'GET_DATA_REQUEST',
    GET_DATA_LIST_SUCESS: 'GET_DATA_LIST_SUCESS',
    GET_DATA_LIST_FAIL: 'GET_DATA_LIST_FAIL',

    UPDATE_DATA_REQUEST: "UPDATE_DATA_REQUEST",
    UPDATE_DATA_LIST_SUCESS: "UPDATE_DATA_LIST_SUCESS",
    UPDATE_DATA_LIST_FAIL: "UPDATE_DATA_LIST_FAIL",

};
// BASE URLS
export const SERVICES_BASE_URL = "https://api-backend-render.onrender.com/data";
