export const ActionTypes = {

    GET_SERIVCE_EXEL_DATA_REQUEST: 'GET_SERIVCE_EXEL_DATA_REQUEST',
    GET_SERIVCE_EXEL_DATA_LIST_SUCESS: 'GET_SERIVCE_EXEL_DATA_LIST_SUCESS',
    GET_SERIVCE_EXEL_DATA_LIST_FAIL: 'GET_SERIVCE_EXEL_DATA_LIST_FAIL',

    GET_BLOG_EXEL_DATA_REQUEST: 'GET_BLOG_EXEL_DATA_REQUEST',
    GET_BLOG_EXEL_DATA_LIST_SUCESS: 'GET_BLOG_EXEL_DATA_LIST_SUCESS',
    GET_BLOG_EXEL_DATA_LIST_FAIL: 'GET_BLOG_EXEL_DATA_LIST_FAIL',


};
// BASE URLS
export const SERVICES_BASE_URL = "/customeData.json";
export const BLOGS_BASE_URL = "/customeData.json";

